### ISSUE TITLE
Push updated release to NPM

### ISSUE THREAD

**Issue by markbirbeck** [dariusk/pos-js#10]
:)

**Comment by markbirbeck** [comment]
Or even better...change the issue title to `Set up CI to automatically deploy to NPM` and let's get this automated. ;)

I'm sure you know how to do this @dariusk, but if you need a hand just shout. I use Wercker for all of my projects and it's pretty easy to get it deploying to NPM on a successful build.

**Comment by dariusk** [comment]
Good idea. I'm most familiar with Travis-CI and use it for a few other projects so I think I'll go with that.

**Comment by dariusk** [comment]
Fixed in 693c0d332dcc314f0a9163cb4a158dbea4d57dfe and with some configuration to the repo. Now as long as a pull request increments the NPM version, the publish should happen automatically.
