### ISSUE TITLE
Rule 2 bails on __proto__

### ISSUE THREAD

**Issue by silentrob** [dariusk/pos-js#15]
This was kinda edgy, but trying to tag `__proto__` returns undefined and crashes. This should probably return Noun or try/catch.

**Comment by Hugo-ter-Doest** [comment]
I agree that the original code is not right. I cannot understand how the result of looking up a word in the lexicon results in a function. So, you are right to check if it is undefined (as before) and for not equal to array. Maybe we need a lookup function that simply returns an empty array or undefined if a word is not in the lexicon.

Regards, Hugo

**Comment by dariusk** [comment]
Fixed in #16
