### ISSUE TITLE
Tagger identifies the name Fred as a VBN

### ISSUE THREAD

**Issue by smalltalk-josh** [dariusk/pos-js#28]
It turn the NNP "Fred" into a VBN. I think it is because it ends in "ed"

```js
var pos = require('pos');
var words = new pos.Lexer().lex('My name is Fred Jenkins');
var tagger = new pos.Tagger();
var taggedWords = tagger.tag(words);
```
expected:
```js
[
  ['My', 'PRP$'],
  ['name', 'NN'],
  ['is', 'VBZ'],
  ['Fred', 'VBN'],
  ['Jenkins', 'NNP']
]
```
actual:
```js
[
  ['My', 'PRP$'],
  ['name', 'NN'],
  ['is', 'VBZ'],
  ['Fred', 'NNP'],
  ['Jenkins', 'NNP']
]
```

**Comment by Hugo-ter-Doest** [comment]
I think you're right: rule number 3 says that if a noun ends in 'ed' it is probably (in most cases) a verb (past participle). You could narrow down the rule to only apply to nouns and not to proper nouns; it tests on the first character of the category. However, you may loose precision in other cases. The set of transformation rules is statistically derived from a corpus.

Hugo
